/* Press JSON structure
 *  Each press object contains the following:
 *      title - string, title of the press article to display
 *      url - string, URL to press article. If NULL, then there should be no link
 *      author - string, author of the press article to display
 *      publication - string, publication of the press article to display
 *      sortDate - string in the form YYYY-MM-DD. Used to sort awards by date
 *      displayDate - string, date to be displayed
 *      featured - string, subject of the article to display as a heading in the "Featured Press" section if featured, use null if not featured
 *      pressLogo - string, filename of logo to display in "Featured Press" section (if featured != null)
 *      relatedPublications - an array of publication id (pub_id) strings. This is currently ignored.
 *      relatedTalks - an array of talk id (talk_id) strings. This is currently ignored.
 *      relatedProjects - an array of project id (proj_id) strings. This allows the projects section of the page to list press for each project.
 */
var pressJSON = [
    {
        "title": "Review: Wally, Moisture Minder",
        "url": "http://www.wired.com/2014/07/wally/",
        "author": "John Brandoon",
        "publication": "Wired",
        "sortDate": "2014-07-18",
        "displayDate": "Jul 2014",
        "featured": "SNUPI Technologies / WallyHome",
        "pressLogo": "img/press/wired.jpg",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Bright Idea: SNUPI Technologies & Wally",
        "url": "http://seattlebusinessmag.com/article/bright-idea-snupi-technologies-wally",
        "author": "John Levesque",
        "publication": "Seattle Business Magazine",
        "sortDate": "2014-03-00",
        "displayDate": "Mar 2014",
        "featured": "SNUPI Technologies / WallyHome",
        "pressLogo": "img/press/SeattleBusinessMag.png",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Review: At home with Wally, a new sensor network for detecting water leaks",
        "url": "http://www.geekwire.com/2014/review-home-test-wally-water-leak-sensor-network/",
        "author": "Kevin Lisota",
        "publication": "GeekWire",
        "sortDate": "2014-02-26",
        "displayDate": "Feb 2014",
        "featured": "SNUPI Technologies / WallyHome",
        "pressLogo": "img/press/GeekWire.png",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Nest Competitor Monitors Your House's Leaks on the Cheap",
        "url": "http://www.technologyreview.com/news/523741/nest-competitor-monitors-your-houses-leaks-on-the-cheap/",
        "author": "Kate Greene",
        "publication": "MIT Technology Review",
        "sortDate": "2014-01-23",
        "displayDate": "Jan 2014",
        "featured": "SNUPI Technologies / WallyHome",
        "pressLogo": "img/press/MIT_TR.png",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "5 Smart Home Startups to Watch",
        "url": "http://www.lightreading.com/mobile/m2m-platforms/5-smart-home-startups-to-watch/d/d-id/707307?f_src=lightreading_gnews",
        "author": "Dan Jones",
        "publication": "Light Reading",
        "sortDate": "2014-01-15",
        "displayDate": "Jan 2014",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "SNUPI Technologies Raises $7.5M from WRF, Madrona to Take Wally to Market",
        "url": "http://www.xconomy.com/seattle/2014/01/13/snupi-technologies-raises-7-5m-from-wrf-madrona-to-take-wally-to-market/",
        "author": "Benjamin Romano",
        "publication": "Xconomy",
        "sortDate": "2014-01-13",
        "displayDate": "Jan 2014",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "SNUPI raises $7.5M for sensor network Wally, looks to detect water leaks in homes",
        "url": "http://www.geekwire.com/2014/snupi-raises-7-5m-series-home-sensor-network-wally/",
        "author": "John Cook",
        "publication": "GeekWire",
        "sortDate": "2014-01-13",
        "displayDate": "Jan 2014",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "SNUPI Technologies gets $7.5M for in-home hazard sensor services",
        "url": "http://www.bizjournals.com/seattle/blog/techflash/2014/01/snupi-technologies-gets-75m-for.html?utm_campaign=Feed%3A+bizj_seattle+%28Puget+Sound+Business+Journal%29&s=article_search&utm_medium=feed&ana=RSS&utm_source=feedburner",
        "author": "Ana Sofia Knauf",
        "publication": "Puget Sound Business Journal",
        "sortDate": "2014-01-13",
        "displayDate": "Jan 2014",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Seattle co. makes wireless sensors to detect moisture in homes",
        "url": "http://www.king5.com/news/technology/Seattles-Snupi-Technologies-joins-the-smart-home-welcome-wagon-240133661.html",
        "author": "Renay San Miguel",
        "publication": "King 5 News",
        "sortDate": "2014-01-14",
        "displayDate": "Jan 2014",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "SNUPI Technologies snags $7.5 mln in Series A funds",
        "url": "http://www.pehub.com/2014/01/snupi-technologies-snags-7-3-mln-in-series-a-funds/",
        "author": "Iris Dorbian",
        "publication": "Reuters",
        "sortDate": "2014-01-13",
        "displayDate": "Jan 2014",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Install moisture sensing wireless system",
        "url": "http://www.examiner.com/article/install-moisture-sensing-wireless-system?cid=rss",
        "author": "Kathleen Story",
        "publication": "Examiner",
        "sortDate": "2014-01-30",
        "displayDate": "Jan 2014",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Ubiquitous Computing (UbiComp) Research Lab: A Computing Research in Action Showcase (video)",
        "url": "http://www.cccblog.org/2014/01/13/ubiquitous-computing-ubicomp-research-lab-a-computing-research-in-action-showcase/",
        "author": "Kenneth Hines",
        "publication": "The Computing Community Consortium (CCC)",
        "sortDate": "2014-01-13",
        "displayDate": "Jan 2014",
        "featured": "SNUPI",
        "pressLogo": "img/press/CCC.png",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "GeekWire’s Gift Guide: 12 geeky gift ideas from Seattle-area designers and startups",
        "url": "http://www.geekwire.com/2013/12-northwest-gifts-geek-love-geekwire-gift-guide-2013/",
        "author": "Monica Guzman",
        "publication": "GeekWire",
        "sortDate": "2013-12-11",
        "displayDate": "Dec 2013",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Seattle’s Big Ideas Belong On Big Napkins",
        "url": "http://www.adpulp.com/seattles-big-ideas-belong-on-big-napkins/",
        "author": "Dan Goldgeier",
        "publication": "AdPulp",
        "sortDate": "2013-12-04",
        "displayDate": "Dec 2013",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "SNUPI Technologies' Home Sensor Network Monitors Water Leaks, Babies",
        "url": "http://www.xconomy.com/seattle/2013/11/15/snupi-technologies-home-sensor-network-monitors-water-leaks-babies/?single_page=true",
        "author": "Benjamin Romano",
        "publication": "Xconomy",
        "sortDate": "2013-11-15",
        "displayDate": "Nov 2013",
        "featured": "SNUPI Technologies / WallyHome",
        "pressLogo": "img/press/xconomy.jpg",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Meet the Seattle 10: These innovative startups are looking to change the world",
        "url": "http://www.geekwire.com/2013/meet-seattle-10-innovative-startups-change-world/",
        "author": "John Cook",
        "publication": "GeekWire",
        "sortDate": "2013-11-14",
        "displayDate": "Nov 2013",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Meet Wally: This $299 low-power sensor network detects water leaks and mold",
        "url": "http://www.geekwire.com/2013/meet-wally-lowpower-wireless-sensor-network-detects-water-leaks-mold/",
        "author": "John Cook",
        "publication": "GeekWire",
        "sortDate": "2013-11-04",
        "displayDate": "Nov 2013",
        "featured": "SNUPI Technologies / WallyHome",
        "pressLogo": "img/press/GeekWire.png",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Next Big Thing: Jeremy Jaech, CEO of SNUPI Technologies",
        "url": "http://www.geekwire.com/2013/big-jeremy-jaech-ceo-snupi-technologies/",
        "author": "Jenni Hogan",
        "publication": "GeekWire",
        "sortDate": "2013-09-16",
        "displayDate": "Sep 2013",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "SNUPI technology keeps a watchful eye on your home",
        "url": "http://www.bizjournals.com/seattle/blog/techflash/2013/08/techflash-cup-snupi-technologies.html",
        "author": "Emily Parkhurst",
        "publication": "Puget Sound Business Journal",
        "sortDate": "2013-09-16",
        "displayDate": "Sep 2013",
        "featured": "SNUPI Technologies / WallyHome",
        "pressLogo": "img/press/PSBJ.gif",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "UW researchers turn LCDs into touchscreen",
        "url": "http://www.dailyuw.com/news/article_315921f6-34c8-557d-962e-29040ed6e5b2.html",
        "author": "Amy Busch",
        "publication": "The Daily",
        "sortDate": "2013-05-14",
        "displayDate": "May 2013",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_utouch" ]
    },
    {
        "title": "A Simple Way to Turn Any LCD into a Touch Screen",
        "url": "http://www.technologyreview.com/news/514061/a-simple-way-to-turn-any-lcd-into-a-touch-screen/",
        "author": "Rachel Metz",
        "publication": "MIT Technology Review",
        "sortDate": "2013-04-24",
        "displayDate": "Apr 2013",
        "featured": "uTouch",
        "pressLogo": "img/press/MIT_TR.png",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_utouch" ]
    },
    {
        "title": "Turning a standard LCD monitor into touchscreen with a $5 wall-mounted sensor",
        "url": "http://www.extremetech.com/computing/154258-turning-a-standard-lcd-monitor-into-touchscreen-with-a-5-wall-mounted-sensor",
        "author": "Sebastian Anthony",
        "publication": "Extreme Tech",
        "sortDate": "2013-04-25",
        "displayDate": "Apr 2013",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_utouch" ]
    },
    {
        "title": "UW Spinout Funded by Madrona To Build Cheap Home Sensor Networks",
        "url": "http://www.xconomy.com/seattle/2012/12/11/uw-spinout-funded-by-madrona-to-build-cheap-home-sensor-networks/",
        "author": "Benjamin Romano",
        "publication": "Xconomy",
        "sortDate": "2012-12-11",
        "displayDate": "Dec 2012",
        "featured": "SNUPI Technologies / WallyHome",
        "pressLogo": "img/press/xconomy.jpg",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "UW sensor spinoff SNUPI takes flight",
        "url": "http://seattletimes.com/html/technologybrierdudleysblog/2019881582_post_61.html",
        "author": "Brier Dudley",
        "publication": "The Seattle Times",
        "sortDate": "2012-12-11",
        "displayDate": "Dec 2012",
        "featured": "SNUPI Technologies / WallyHome",
        "pressLogo": "img/press/SeattleTimes.jpg",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Serial Entrepreneur Jeremy Jaech Launches new company with UW Professor Shwetak Patel",
        "url": "http://seattlebusinessmag.com/blog/serial-entrepreneur-jeremy-jaech-launches-new-company-uw-professor-shwetak-patel",
        "author": "Leslie Helm",
        "publication": "Seattle Business Magazine",
        "sortDate": "2012-12-11",
        "displayDate": "Dec 2012",
        "featured": "SNUPI Technologies / WallyHome",
        "pressLogo": "img/press/SeattleBusinessMag.png",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "SNUPI Technologies, latest company to spin out of UW, gets $1.5M in funding",
        "url": "http://www.bizjournals.com/seattle/blog/techflash/2012/12/snupi-technologies-latest-company-to.html",
        "author": "Emily Parkhurst",
        "publication": "Puget Sound Business Journal",
        "sortDate": "2012-12-11",
        "displayDate": "Dec 2012",
        "featured": "SNUPI Technologies / WallyHome",
        "pressLogo": "img/press/PSBJ.gif",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Jeremy Jaech’s new home sensor startup SNUPI lands $1.5M from Madrona, others",
        "url": "http://www.geekwire.com/2012/jeremy-jaechs-home-sensor-startup-snupi-lands-15m-madrona/",
        "author": "John Cook",
        "publication": "GeekWire",
        "sortDate": "2012-12-11",
        "displayDate": "Dec 2012",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Jeremy Jaech, Shwetak Patel form UW home sensor spin out WatchFrog",
        "url": "http://www.geekwire.com/2012/jeremy-jaech-shwetak-patel-form-uw-spin-watchfrog/",
        "author": "John Cook",
        "publication": "GeekWire",
        "sortDate": "2012-09-28",
        "displayDate": "Sep 2012",
        "featured": "SNUPI Technologies / WallyHome",
        "pressLogo": "img/press/GeekWire.png",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Turning the Body Into a Wireless Controller",
        "url": "http://www.cccblog.org/2012/05/25/turning-the-body-into-a-wireless-controller/",
        "author": "Erwin Gianchandani",
        "publication": "The Computing Community Consortium (CCC)",
        "sortDate": "2012-05-25",
        "displayDate": "May 2012",
        "featured": "Humantenna",
        "pressLogo": "img/press/CCC.png",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "Beyond Kinect: Gestural computer spells keyboard death",
        "url": "http://www.newscientist.com/article/mg21428645.500-beyond-kinect-gestural-computer-spells-keyboard-death.html",
        "author": "Jim Giles",
        "publication": "New Scientist",
        "sortDate": "2012-05-15",
        "displayDate": "May 2012",
        "featured": "Humantenna",
        "pressLogo": "img/press/NewScientist.jpg",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "Microsoft Research aims to turn any laptop into a Kinect",
        "url": "http://news.techworld.com/personal-tech/3357624/microsoft-project-aims-turn-any-laptop-into-kinect/",
        "author": "Nick Barber",
        "publication": "TechWorld",
        "sortDate": "2012-05-15",
        "displayDate": "May 2012",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "Microsoft Research projects offer new takes on gesture sensing",
        "url": "https://youtu.be/em-nvzxzC68?list=UU7iialY1qmmcyFWilHAEVpA",
        "author": "Nick Barber",
        "publication": "IDG News Service",
        "sortDate": "2012-05-09",
        "displayDate": "May 2012",
        "featured": "Humantenna",
        "pressLogo": "img/press/IDG.jpg",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "Gesture Sensing Alternatives Use Radio Interference, Doppler Effect",
        "url": "http://www.pcworld.com/article/255310/gesture_sensing_alternatives_use_radio_interference_doppler_effect.html",
        "author": "Nick Barber",
        "publication": "PCWorld",
        "sortDate": "2012-05-09",
        "displayDate": "May 2012",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "Cool Microsoft Research Takes Kinect to Another Level",
        "url": "http://www.pcmag.com/article2/0,2817,2404093,00.asp",
        "author": "Mark Hachman",
        "publication": "PC Magazine",
        "sortDate": "2012-05-07",
        "displayDate": "May 2012",
        "featured": "Humantenna",
        "pressLogo": "img/press/PCMag.gif",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "ACM User Conference Seeks the Magic in User Interfaces",
        "url": "http://www.pcworld.com/article/255130/acm_user_conference_seeks_the_magic_in_user_interfaces.html",
        "author": "Nick Barber and Joab Jackson",
        "publication": "PCWorld",
        "sortDate": "2012-05-07",
        "displayDate": "May 2012",
        "featured": "Humantenna",
        "pressLogo": "img/press/PCWorld.png",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "Better typing while walking, and other cool stuff from UW",
        "url": "http://www.geekwire.com/2011/typing-walking-cool-stuff-uw-students",
        "author": "Todd Bishop",
        "publication": "GeekWire",
        "sortDate": "2011-10-20",
        "displayDate": "Oct 2011",
        "featured": "Humantenna",
        "pressLogo": "img/press/GeekWire.png",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "Remote Control, With a Wave of a Hand",
        "url": "http://www.nytimes.com/2011/09/11/business/using-gestures-to-control-electronic-devices.html",
        "author": "Anne Eisenberg",
        "publication": "The New York Times",
        "sortDate": "2011-09-10",
        "displayDate": "Sep 2011",
        "featured": "Humantenna",
        "pressLogo": "img/press/NYT.jpg",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "Electromagnetic Fields Offer Next Big Controller Gimmick",
        "url": "http://www.escapistmagazine.com/news/view/109928-Electromagnetic-Fields-Offer-Next-Big-Controller-Gimmick",
        "author": "Earnest Cavalli",
        "publication": "The Escapist",
        "sortDate": "2011-05-11",
        "displayDate": "May 2011",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "Microsoft Sees Human Body as an Antenna",
        "url": "http://www.livescience.com/14204-microsoft-human-antenna.html",
        "author": "Leslie Meredith",
        "publication": "LiveScience.com",
        "sortDate": "2011-05-17",
        "displayDate": "May 2011",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "CHI '11: Enhancing the Human Condition",
        "url": "http://www.rdmag.com/News/Feeds/2011/05/information-tech-chi-11-enhancing-the-human-condition/",
        "author": null,
        "publication": "R&D Magazine",
        "sortDate": "2011-05-10",
        "displayDate": "May 2011",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "Turn your home into a giant game controller",
        "url": "http://news.cnet.com/turn-your-home-into-a-giant-game-controller/8301-17938_105-20062056-1.html",
        "author": "Tim Hornyak",
        "publication": "CNET News",
        "sortDate": "2011-05-12",
        "displayDate": "May 2011",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "Making Your Wall An Input Device",
        "url": "http://blogs.wsj.com/tech-europe/2011/05/13/making-your-wall-an-input-device/?mod=google_news_blog",
        "author": "Ben Rooney",
        "publication": "The Wall Street Journal",
        "sortDate": "2011-05-13",
        "displayDate": "May 2011",
        "featured": "Humantenna",
        "pressLogo": "img/press/WSJ.jpg",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "If You Could Talk To Walls - Your Body As An Antenna",
        "url": "http://inventorspot.com/articles/if_you_could_talk_walls_your_body_antenna",
        "author": "Jaime Reygie",
        "publication": "InventorSpot",
        "sortDate": "2011-05-00",
        "displayDate": "May 2011",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "Now, control home appliances single-handedly with 'human antenna'",
        "url": "http://www.sify.com/news/now-control-home-appliances-single-handedly-with-human-antenna-news-international-lfnoEjfcgdd.html",
        "author": null,
        "publication": "Sify News",
        "sortDate": "2011-05-13",
        "displayDate": "May 2011",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "Could Microsoft Turn Our Bodies into Antennas?",
        "url": "http://techland.time.com/2011/05/11/could-microsoft-turn-our-bodies-into-antennas/",
        "author": "Matt Peckham",
        "publication": "TIME",
        "sortDate": "2011-05-11",
        "displayDate": "May 2011",
        "featured": "Humantenna",
        "pressLogo": "img/press/TIME.jpg",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "How to make a human antenna",
        "url": "http://news.discovery.com/tech/human-antenna-electromagnetic-interference-110512.htm",
        "author": "Alyssa Danigelis",
        "publication": "Discovery News",
        "sortDate": "2011-05-12",
        "displayDate": "May 2011",
        "featured": "Humantenna",
        "pressLogo": "img/press/discovery.jpg",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "Microsoft to turn your flat into a control pad",
        "url": "http://www.reghardware.com/2011/05/11/microsoft_household_surfaces_become_control_panels/",
        "author": "Caleb Cox",
        "publication": "The Register Hardware",
        "sortDate": "2011-05-11",
        "displayDate": "May 2011",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "Microsoft motion controller concept kicks sand in Kinect's puny face",
        "url": "http://www.engadget.com/2011/05/11/microsoft-motion-controller-concept-kicks-sand-in-kinects-puny/",
        "author": "Brian Heater",
        "publication": "Engadget",
        "sortDate": "2011-05-11",
        "displayDate": "May 2011",
        "featured": "Humantenna",
        "pressLogo": "img/press/engadget.png",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "Turn everyday objects into touch-sensitive controllers",
        "url": "http://gizmodo.com/5800596/turn-everyday-objects-into-touch+sensitive-controllers",
        "author": "Kelly Hodgkins",
        "publication": "Gizmodo",
        "sortDate": "2011-05-10",
        "displayDate": "May 2011",
        "featured": "Humantenna",
        "pressLogo": "img/press/gizmodo.png",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "Turn your entire home into a game controller",
        "url": "http://www.newscientist.com/blogs/onepercent/2011/05/jim-giles-contributor-vancouve.html",
        "author": "Jim Giles",
        "publication": "New Scientist",
        "sortDate": "2011-05-10",
        "displayDate": "May 2011",
        "featured": "Humantenna",
        "pressLogo": "img/press/NewScientist.jpg",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "Talking to the Wall: An experimental interface from Microsoft turns any wall into an interactive surface",
        "url": "http://www.technologyreview.com/news/423905/talking-to-the-wall/",
        "author": "Kate Greene",
        "publication": "MIT Technology Review",
        "sortDate": "2011-05-03",
        "displayDate": "May 2011",
        "featured": "Humantenna",
        "pressLogo": "img/press/MIT_TR.png",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_humantenna" ]
    },
    {
        "title": "A New Home Network",
        "url": null,
        "author": "Alex Hutchinson",
        "publication": "Popular Mechanics",
        "sortDate": "2010-12-00",
        "displayDate": "Dec 2010",
        "featured": "SNUPI",
        "pressLogo": "img/press/PopularMech.jpg",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": []
    },
    {
        "title": "Sensors Use Building's Electrical Wiring as Antenna",
        "url": "http://www.technologyreview.com/news/420870/sensors-use-buildings-electrical-wiring-as-antenna/",
        "author": "Kate Greene",
        "publication": "MIT Technology Review",
        "sortDate": "2010-09-21",
        "displayDate": "Sep 2010",
        "featured": "SNUPI",
        "pressLogo": "img/press/MIT_TR.png",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Home's electrical wiring acts as antenna to receive low-power sensor data",
        "url": "http://www.washington.edu/news/2010/09/15/homes-electrical-wiring-acts-as-antenna-to-receive-low-power-sensor-data/",
        "author": "Hannah Hickey",
        "publication": "UW News",
        "sortDate": "2010-09-15",
        "displayDate": "Sep 2010",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Home wiring as an antenna: Discovery spawns UW startup",
        "url": "http://www.bizjournals.com/seattle/blog/techflash/2010/09/new_startup_from_uw_to_use_home_electrical_wiring_as_antenna.html",
        "author": "Todd Bishop",
        "publication": "Puget Sound Business Journal",
        "sortDate": "2010-09-15",
        "displayDate": "Sep 2010",
        "featured": "SNUPI",
        "pressLogo": "img/press/PSBJ.gif",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "UW team develops sensors with 50-year batteries",
        "url": "http://seattletimes.nwsource.com/html/technologybrierdudleysblog/2012908830_uw_team_develops_sensors_with.html?syndication=rss",
        "author": "Brier Dudley",
        "publication": "The Seattle Times",
        "sortDate": "2010-09-15",
        "displayDate": "Sep 2010",
        "featured": "SNUPI",
        "pressLogo": "img/press/SeattleTimes.jpg",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "SNUPI's Smart-Home Sensors Communicate Via the Copper Already in the Walls",
        "url": "http://www.popsci.com/technology/article/2010-09/snupis-low-power-smart-home-sensors-communicate-copper-wiring-walls",
        "author": "Clay Dillow",
        "publication": "Popular Science",
        "sortDate": "2010-09-15",
        "displayDate": "Sep 2010",
        "featured": "SNUPI",
        "pressLogo": "img/press/PopularSci.jpg",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Researchers Turn Home Electrical Wiring Into Antenna for Sensor",
        "url": "http://www.ibtimes.com/articles/62678/20100915/sensing-wireless-devices-electrical-wiring-innovation-university-of-washington-snupi.htm",
        "author": "Gabriel Perna",
        "publication": "International Business Times",
        "sortDate": "2010-09-16",
        "displayDate": "Sep 2010",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Built-In Electrical Wiring Could Directly Monitor Home Energy Use",
        "url": "http://inhabitat.com/2010/09/16/electrical-wiring-could-monitor-your-home/",
        "author": "Ariel Schwartz",
        "publication": "Inhabitat",
        "sortDate": "2010-09-16",
        "displayDate": "Sep 2010",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Turning Your Home Wiring Into a Giant Antenna",
        "url": "http://mobile.slashdot.org/story/10/09/16/1722204/Turning-Your-Home-Wiring-Into-a-Giant-Antenna",
        "author": null,
        "publication": "Slashdot",
        "sortDate": "2010-09-16",
        "displayDate": "Sep 2010",
        "featured": "SNUPI",
        "pressLogo": "img/press/slashdot.svg",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Smart home sensors use electrical wiring as an antenna",
        "url": "http://www.gizmag.com/home-electrical-wiring-as-antenna/16388/",
        "author": "Darren Quick",
        "publication": "Gizmag",
        "sortDate": "2010-09-16",
        "displayDate": "Sep 2010",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Home's electrical wiring acts as antenna to receive low-power sensor data",
        "url": "http://www.rdmag.com/News/2010/09/Information-Tech-Wireless-Home-s-electrical-wiring-acts-as-antenna-to-receive-low-power-sensor-data/",
        "author": null,
        "publication": "R&D Magazine",
        "sortDate": "2010-09-16",
        "displayDate": "Sep 2010",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "An Antenna Breakthrough",
        "url": "http://newenergyandfuel.com/2010/09/24/an-antenna-breakthrough/",
        "author": null,
        "publication": "New Energy and Fuel",
        "sortDate": "2010-09-24",
        "displayDate": "Sep 2010",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Low-power sensor data over power lines",
        "url": "http://eetweb.com/energy-monitoring/SNUPI_092410/",
        "author": null,
        "publication": "Energy Efficiency & Technology (EET)",
        "sortDate": "2010-09-24",
        "displayDate": "Sep 2010",
        "featured": null,
        "pressLogo": null,
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    },
    {
        "title": "Home's Electrical Wiring Acts as Antenna to Receive Low-Power Sensor Data",
        "url": "http://cacm.acm.org/news/98897-homes-electrical-wiring-acts-as-antenna-to-receive-low-power-sensor-data/fulltext",
        "author": null,
        "publication": "Communications of the ACM",
        "sortDate": "2010-09-16",
        "displayDate": "Sep 2010",
        "featured": "SNUPI",
        "pressLogo": "img/press/CACM.png",
        "relatedPublications": [],
        "relatedTalks": [],
        "relatedProjects": [ "proj_snupi" ]
    }
];
